logging:
  level:
    net.arcatanium: INFO

spring:
  application:
    name: regalo
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/config/data.sqlite3
  jpa:
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        ddl-auto: update
        jdbc:
          batch_size: 1000
        order_updates: true
        order_inserts: true