CREATE TABLE WISHLIST (
    WISHLIST_ID          BLOB      PRIMARY KEY,
    NAME                 TEXT      NOT NULL,
    INSERTTIMESTAMP      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LASTUPDATEDTIMESTAMP TIMESTAMP,
    VERSION              INTEGER
);

CREATE TABLE WISHLIST_ITEM (
    SEQUENCE_NUM         INTEGER   NOT NULL,
    WISHLIST_ID          BLOB      NOT NULL,
    NAME                 TEXT,
    DESCRIPTION          TEXT,
    URL                  TEXT,
    INSERTTIMESTAMP      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LASTUPDATEDTIMESTAMP TIMESTAMP,
    PRIMARY KEY (SEQUENCE_NUM, WISHLIST_ID),
    FOREIGN KEY (WISHLIST_ID) REFERENCES WISHLIST (WISHLIST_ID)
);