CREATE TABLE WISHLIST (
    WISHLIST_ID TEXT PRIMARY KEY,
    NAME        TEXT NOT NULL
);

CREATE TABLE WISHLIST_ITEMS (
    WISHLIST_ITEM_ID TEXT PRIMARY KEY,
    NAME             TEXT,
    DESCRIPTION      TEXT,
    URL              TEXT,
    WISHLIST_ID      TEXT NOT NULL,
    FOREIGN KEY (WISHLIST_ID) REFERENCES WISHLIST (WISHLIST_ID)
);